# Site settings
title: Chaz6chez's Blog
description: "I sot u'r soul free. "
baseurl: "https://chaz6chez.cn"
url: "https://www.chaz6chez.cn"
favicon: /images/favicon.ico

# User settings
username: Chaz6chez
user_title: Back-End Engineer
email: 250220719@qq.com
github_username:  chaz6chez
zhihu_username:  chaz6chez
profile_picture: /images/avatar.jpg"

# valine
valine_enable: true
valine_appid: '9ezjjBFDS7WDBFuQd5cmguts-gzGzoHsz'
valine_appkey: 'aGuQp34CBAhgakzz42duUbsb'

# Build settings
markdown: kramdown
highlighter: rouge
permalink: date #/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  math_engine: mathjax
  syntax_highlighter: rouge

  input: GFM
  hard_wrap: false

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: é¦–é¡µ
      url: /
      key_trigger: ğŸ 
    - title: ç›®å½•
      url: /posts
      key_trigger: ğŸ“ƒ
    - title: å½’æ¡£
      url: /series
      key_trigger: ğŸ“‚
    - title: æ ‡ç­¾
      url: /tags
      key_trigger: ğŸ·ï¸
    - title: å…³äºæˆ‘
      url: /about
      key_trigger: ğŸ°

  section_2:
    - title: Github
      url: https://github.com/chaz6chez
      external: true
      key_trigger: ğŸ’»
    - title: æˆ‘çš„çŸ¥ä¹
      url: https://www.zhihu.com/people/chaz6chez
      key_trigger: ğŸ™‹
      external: true
    - title: ç½‘æ˜“äº‘
      url: https://music.163.com/#/artist?id=34679151
      key_trigger: ğŸµ
      external: true
    - title: èˆªæ‹
      url: https://www.skypixel.com/users/250220719
      key_trigger: ğŸ“¹
      external: true

  section_3:
    - title: PHP
      url: https://www.php.net/
      key_trigger: ğŸ’»
      external: true

    - title: Golang
      url: https://golang.google.cn/
      key_trigger: ğŸ’»
      external: true

    - title: Python
      url: https://www.python.org/
      key_trigger: ğŸ’»
      external: true

# projects in header index
projects:
  - title: chaz6chez/structure
    url: https://github.com/chaz6chez/structure
    desc: åŸºäºPHPåå°„çš„æ•°æ®éªŒè¯å™¨

  - title: workbunny/event-loop
    url: https://github.com/workbunny/event-loop
    desc: åŸºäºPHPå¼€å‘çš„è½»é‡çº§é«˜æ€§èƒ½äº‹ä»¶å¾ªç¯åº“

  - title: workbunny/nacos
    url: https://github.com/workbunny/webman-nacos
    desc: Nacosçš„Webmanå®¢æˆ·ç«¯æ’ä»¶

  - title: walkor/rabbitmq
    url: https://github.com/walkor/rabbitmq
    desc: Workermanå®˜æ–¹RabbitMQå¼‚æ­¥å®¢æˆ·ç«¯ç»„ä»¶

  - title: casual/database
    url: https://github.com/chaz6chez/casual-database
    desc: PHPå¸¸é©»å†…å­˜å¼€å‘çš„MySQLè¿æ¥ä»¶

  - title: Workbunny
    url: /chaz6chez/2022/03/07/WorkbunnysProjectPlan.html
    desc: åŸºäºGolangå¼€å‘çš„è½»é‡çº§é«˜æ€§èƒ½ä»»åŠ¡è°ƒåº¦æœåŠ¡
    highlight: Plan

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
