# Site settings
title: Chaz6chez's Blog
description: "I sot u'r soul free. "
baseurl: "https://chaz6chez.cn"
url: "https://www.chaz6chez.cn"

# User settings
username: chaz6chez
user_title: Back-End Engineer
email: 250220719@qq.com
github_username:  chaz6chez
disqus_username: loremipsum
profile_picture: /images/avatar.jpg"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: é¦–é¡µ
      url: /
      key_trigger: ğŸ 
    - title: åšå®¢
      url: /posts
      key_trigger: ğŸ“–
    - title: å½’æ¡£
      url: /series
      key_trigger: ğŸ—„ï¸
    - title: æ ‡ç­¾
      url: /tags
      key_trigger: ğŸ·ï¸
    - title: å…³äºæˆ‘
      url: /about
      key_trigger: ğŸ˜‚
  section_2:
    - title: Github
      url: https://github.com/chaz6chez
      new_tab: true
      key_trigger: g
    - title: çŸ¥ä¹
      url: https://www.zhihu.com/people/chaz6chez
      key_trigger: z
    - title: ç½‘æ˜“äº‘
      url: https://music.163.com/#/artist?id=34679151
      key_trigger: w
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

  section_3:
    - title: PHP
      url: https://www.php.net/
      external: true
    - title: Golang
      url: https://golang.google.cn/
      external: true
    - title: Python
      url: https://www.python.org/
      external: true

# projects in header index
projects:
  - title: chaz6chez/structure
    url: https://github.com/chaz6chez/structure
    desc: ä¸€ä¸ªåŸºäºPHPæ•°ç»„ã€åå°„æœºåˆ¶çš„æ•°æ®ç»“æ„ï¼Œå¯ç”¨äºå‚æ•°éªŒè¯ã€è¿‡æ»¤ã€è½¬æ¢

  - title: casual/database
    url: https://github.com/chaz6chez/casual-database
    desc: A Long-living MySQL connection for daemon base on PHP

  - title: workbunny/nacos
    url: https://github.com/workbunny/webman-nacos
    desc: Webmançš„Nacoså®¢æˆ·ç«¯æ’ä»¶åŒ…

  - title: walkor/rabbitmq
    url: https://github.com/walkor/rabbitmq
    desc: Workermanå®˜æ–¹RabbitMQå¼‚æ­¥å®¢æˆ·ç«¯ç»„ä»¶

  - title: Workbunny
    url: è®¡åˆ’-workbunnyé¡¹ç›®è®¡åˆ’
    desc: åŸºäºGolangå¼€å‘çš„è½»é‡çº§é«˜æ€§èƒ½ä»»åŠ¡è°ƒåº¦æœåŠ¡
    highlight: Plan

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
